### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by gamesbook** [SimonSapin/cairocffi#41]
I am trying to install in a clean virtualenv. I tried  `pip install cairocffi`.

I get the following error (copied from the tail of the pip.log)
```
Exception information:
Traceback (most recent call last):
  File "/home/creation/.virtualenvs/proto/local/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/home/creation/.virtualenvs/proto/local/lib/python2.7/site-packages/pip/commands/install.py", line 241, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/home/creation/.virtualenvs/proto/local/lib/python2.7/site-packages/pip/req.py", line 1298, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/home/creation/.virtualenvs/proto/local/lib/python2.7/site-packages/pip/req.py", line 625, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/home/creation/.virtualenvs/proto/local/lib/python2.7/site-packages/pip/util.py", line 670, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /home/creation/.virtualenvs/proto/bin/python -c "import setuptools;__file__='/home/creation/.virtualenvs/proto/build/cffi/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vYXHD_-record/install-record.txt --single-version-externally-managed --install-headers /home/creation/.virtualenvs/proto/include/site/python2.7 failed with error code 1 in /home/creation/.virtualenvs/proto/build/cffi
```

If its at all useful, the last few line of the install output were:
```
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-i686-2.7/c/_cffi_backend.o

c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1
```

**Comment by Noelou93** [comment]
U GET RIGHT @SimonSapin !
Thanks boss.

**Comment by Al-Ouest** [comment]
Thx SimonSapin
