### ISSUE TITLE
cairocffi throws on import when xcffib is installed

### ISSUE THREAD

**Issue by tobyp** [SimonSapin/cairocffi#58]
Greetings,
It seems cairocffi and xcffib are not/no longer compatible. Importing cairocffi with xcffib installed (both current versions, via pip) causes an Exception to be thrown:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.4/site-packages/cairocffi/__init__.py", line 105, in <module>
        from .xcb import XCBSurface
      File "/usr/lib/python3.4/site-packages/cairocffi/xcb.py", line 16, in <module>
        ffi.include(xcb_ffi)
      File "/usr/lib/python3.4/site-packages/cffi/api.py", line 430, in include
        type(ffi_to_include).__name__,))
    TypeError: ffi.include() expects an argument that is also of type cffi.FFI, not 'CompiledFFI'

[1] suggests that the call to .include() is undesirable in runtime code, though I'm not experienced enough with cffi to be sure.

ArchLinux // Python 3.4.3 // pip 6.1.1 // cairocffi 0.6 // xcffib 0.3.1 (both installed via pip, not pacman)

[1] https://cffi.readthedocs.org/en/latest/cdef.html#ffi-include-combining-multiple-cffi-interfaces

**Comment by SimonSapin** [comment]
@tych0, any idea what’s going on?

**Comment by tych0** [comment]
Yes, the xcffib 0.3 series has been updated to be cffi 1.0 compatible, but cffi 1.0 breaks compatibility with previous cffis and libraries using them. We're keeping xcffib 0.2.* around for a while and backporting everything to be compatible with cffi <1.0, so I'd stick with the 0.2 series for now.

I think @flacjacket is planning on looking at upgrading cairocffi to 1.0 compatibility at some point, but we're still working out the details in xcffib, so it may not be for a little bit.

**Comment by tych0** [comment]
One fix might be for now to release a cairocffi which declares a max version <0.3 for xcffib and <1.0 for cffi (that's what we've done in qtile, since that needs cairocffi and xcffib to be on 1.0 before it can be ported).

**Comment by flacjacket** [comment]
Right, we switched xcffib to use the new cffi-1.0 out-of-line declarations [1], and while it is nice and simplifies packaging, it has the unfortunate side effect of breaking anything that `ffi.include()`'s it without also switching to the out-of-line declarations. I have been working on a patch for cairocffi [2], we just finished up some bugs getting xcffib working with the new cffi stuff, so I will open that soon when I can be sure it is working.

Installing xcffib < 0.3 (even with the latest cffi) will work for now until cairocffi is updated.

[1] http://cffi.readthedocs.org/en/latest/overview.html#out-of-line-example-abi-level-out-of-line
[2] https://github.com/flacjacket/cairocffi/tree/cffi-1.0

**Comment by SimonSapin** [comment]
> I have been working on a patch for cairocffi [2]

Awesome! I’ve been meaning to look at CFFI 1.0, but I’ll just wait for your PR :)

**Comment by ChillarAnand** [comment]
Is this fixed. I am using latest version. Still it is throwing same error.

```py
Traceback (most recent call last):
  File "indic_scribe.py", line 7, in <module>
    from cffi_wrapper import *
  File "/home/anand/projects/python/ocr/chamanti_ocr/cffi_wrapper.py", line 5, in <module>
    ffi.include(cairocffi.ffi)
  File "/home/anand/.virtualenvs/34/lib/python3.4/site-packages/cffi/api.py", line 490, in include
    type(ffi_to_include).__name__,))
TypeError: ffi.include() expects an argument that is also of type cffi.FFI, not 'CompiledFFI'
```
