### ISSUE TITLE
ImportError: No module named setuptools_ext 

### ISSUE THREAD

**Issue by ceremcem** [SimonSapin/cairocffi#67]
Trying to compile `cairocffi` throws following exception: 

```
    ImportError: No module named setuptools_ext
```

I didn't manage to understand what `setuptools_ext` is and to find it in a python package.

**Comment by SimonSapin** [comment]
Could you copy/paste the exact command you are running and the entire output? Thanks!

**Comment by ceremcem** [comment]
```
ceremcem@cca-erik:cairocffi$ sudo python setup.py install 
[sudo] password for ceremcem: 

Installed /home/ceremcem/cca-sync/dev/cairocffi/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg
/usr/local/lib/python2.7/dist-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py:316: UserWarning: Module cffi was already imported from /usr/local/lib/python2.7/dist-packages/cffi-1.0.dev2-py2.7-linux-x86_64.egg/cffi/__init__.pyc, but /home/ceremcem/cca-sync/dev/cairocffi/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg is being added to sys.path
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    **cffi_args
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 272, in __init__
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 327, in finalize_options
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
ImportError: No module named setuptools_ext
```

**Comment by SimonSapin** [comment]
I have no idea, sorry :/ I have never seen this error. That said, I always use `pip install` rather than running `setup.py` directly.

**Comment by ceremcem** [comment]
It doesn't change the process: 

```
ceremcem@cca-erik:setuptools-18.0.1$ sudo pip install cairocffi
Downloading/unpacking cairocffi
  Downloading cairocffi-0.7.1.tar.gz (76kB): 76kB downloaded
  Running setup.py (path:/tmp/user/0/pip-build-3M6pKQ/cairocffi/setup.py) egg_info for package cairocffi
    /usr/local/lib/python2.7/dist-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py:19: UserWarning: Module cffi was already imported from /usr/local/lib/python2.7/dist-packages/cffi-1.0.dev2-py2.7-linux-x86_64.egg/cffi/__init__.pyc, but /tmp/user/0/easy_install-1Vn7G1/cffi-1.1.2 is being added to sys.path
    
    Installed /tmp/user/0/pip-build-3M6pKQ/cairocffi/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg
    /usr/local/lib/python2.7/dist-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py:316: UserWarning: Module cffi was already imported from /usr/local/lib/python2.7/dist-packages/cffi-1.0.dev2-py2.7-linux-x86_64.egg/cffi/__init__.pyc, but /tmp/user/0/pip-build-3M6pKQ/cairocffi/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg is being added to sys.path
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/user/0/pip-build-3M6pKQ/cairocffi/setup.py", line 65, in <module>
        **cffi_args
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 272, in __init__
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 327, in finalize_options
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load
      File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve
    ImportError: No module named setuptools_ext
    Complete output from command python setup.py egg_info:
    /usr/local/lib/python2.7/dist-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py:19: UserWarning: Module cffi was already imported from /usr/local/lib/python2.7/dist-packages/cffi-1.0.dev2-py2.7-linux-x86_64.egg/cffi/__init__.pyc, but /tmp/user/0/easy_install-1Vn7G1/cffi-1.1.2 is being added to sys.path



Installed /tmp/user/0/pip-build-3M6pKQ/cairocffi/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg

/usr/local/lib/python2.7/dist-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py:316: UserWarning: Module cffi was already imported from /usr/local/lib/python2.7/dist-packages/cffi-1.0.dev2-py2.7-linux-x86_64.egg/cffi/__init__.pyc, but /tmp/user/0/pip-build-3M6pKQ/cairocffi/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg is being added to sys.path

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/user/0/pip-build-3M6pKQ/cairocffi/setup.py", line 65, in <module>

    **cffi_args

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 272, in __init__

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 327, in finalize_options

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2355, in load

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2361, in resolve

ImportError: No module named setuptools_ext

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/user/0/pip-build-3M6pKQ/cairocffi
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by ceremcem** [comment]
Success: 

```
ceremcem@cca-erik:cairocffi$ sudo rm -r /usr/local/lib/python2.7/dist-packages/cffi-1.0.dev2-py2.7-linux-x86_64.egg/
[sudo] password for ceremcem: 
ceremcem@cca-erik:cairocffi$ sudo apt-get install python-setuptools^C
ceremcem@cca-erik:cairocffi$ ^C
ceremcem@cca-erik:cairocffi$ sudo pip install cairocffi
Downloading/unpacking cairocffi
  Downloading cairocffi-0.7.1.tar.gz (76kB): 76kB downloaded
  Running setup.py (path:/tmp/user/0/pip-build-ITvi0T/cairocffi/setup.py) egg_info for package cairocffi
    /usr/local/lib/python2.7/dist-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py:19: UserWarning: Module cffi was already imported from /usr/lib/python2.7/dist-packages/cffi/__init__.pyc, but /tmp/user/0/easy_install-oFJPor/cffi-1.1.2 is being added to sys.path
    
    Installed /tmp/user/0/pip-build-ITvi0T/cairocffi/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg
    /usr/local/lib/python2.7/dist-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py:316: UserWarning: Module cffi was already imported from /usr/lib/python2.7/dist-packages/cffi/__init__.pyc, but /tmp/user/0/pip-build-ITvi0T/cairocffi/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg is being added to sys.path
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files found matching 'cairocffi/_ffi*.py'
Downloading/unpacking cffi>=1.1.0 (from cairocffi)
  Downloading cffi-1.1.2.tar.gz (326kB): 326kB downloaded
  Running setup.py (path:/tmp/user/0/pip-build-ITvi0T/cffi/setup.py) egg_info for package cffi
    
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/dist-packages/pycparser-2.12-py2.7.egg (from cffi>=1.1.0->cairocffi)
Installing collected packages: cairocffi, cffi
  Running setup.py install for cairocffi
    /usr/local/lib/python2.7/dist-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py:316: UserWarning: Module cffi was already imported from /usr/lib/python2.7/dist-packages/cffi/__init__.pyc, but /tmp/user/0/pip-build-ITvi0T/cairocffi/.eggs/cffi-1.1.2-py2.7-linux-x86_64.egg is being added to sys.path
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files found matching 'cairocffi/_ffi*.py'
  Found existing installation: cffi 0.8.6
    Not uninstalling cffi at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py install for cffi
    building '_cffi_backend' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/c/_cffi_backend.o -lffi -o build/lib.linux-x86_64-2.7/_cffi_backend.so
    
Successfully installed cairocffi cffi
Cleaning up...
```
