### ISSUE TITLE
Unable to install 0.6 version

### ISSUE THREAD

**Issue by ChillarAnand** [SimonSapin/cairocffi#82]
I am trying to install in python3.4 virtuanenv and it is failing with this error.

```py
(34)
# anand at anand in ~/projects/python/ocr/chamanti_ocr on git:master x [15:46:38]
$ pip3 install cairocffi==0.6
Traceback (most recent call last):
  File "/home/anand/.virtualenvs/34/bin/pip3", line 7, in <module>
    from pip import main
  File "/home/anand/.virtualenvs/34/lib/python3.4/site-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/anand/.virtualenvs/34/lib/python3.4/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/anand/.virtualenvs/34/lib/python3.4/site-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/home/anand/.virtualenvs/34/lib/python3.4/site-packages/pip/_vendor/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/anand/.virtualenvs/34/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
    import OpenSSL.SSL
  File "/home/anand/.virtualenvs/34/lib/python3.4/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/anand/.virtualenvs/34/lib/python3.4/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/anand/.virtualenvs/34/lib/python3.4/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/anand/.virtualenvs/34/lib/python3.4/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
AttributeError: 'module' object has no attribute '_init_cffi_1_0_external_module'
```

**Comment by ChillarAnand** [comment]
Closing as it was a pip issue.
